changelog:
  categories:            # 릴리즈 노트 분류 설정
    - title: Bug Fixes   # 릴리즈 노트에 'Bug Fixes'라는 분류를 작성한다.
      labels:            # 'Bug Fixes'에 기재할 풀 리퀘스트 레이블을 지정한다.
        - bug
        - fixes
        - test