name: CI/CD 파이프라인 - 버전 업데이트 및 릴리즈

on:
  push:
    branches: [ "main" ] # main 브랜치에 푸시될 때 워크플로우를 트리거합니다.

jobs:
  pre-version:
    name: 현재 파일 버전 로드
    runs-on: ubuntu-latest
    outputs:
      pre-version: ${{ steps.read-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 태그 및 전체 히스토리를 가져오기 위해 필요
      - name: VERSION 파일에서 현재 버전 추출
        id: read-version
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const versionFile = './VERSION';
            const version = fs.readFileSync(versionFile, 'utf8').trim();
            core.setOutput('version', version);

  load-commit-message:
    name: 커밋 메시지 로드
    runs-on: ubuntu-latest
    needs: ["pre-version"]
    if: ${{ needs.pre-version.outputs.pre-version != '' }} 
    outputs:
      commit-message: ${{ steps.check.outputs.commit-message }}
    steps:
      - uses: actions/checkout@v4 # 최신 버전 사용 권장
      - name: Check commit message
        id: check
        run: echo "commit-message=$(echo '${{ github.event.head_commit.message }}')" >> $GITHUB_OUTPUT
        shell: bash

  load-log:
    name: 로그에서 커밋된 로그 로드
    runs-on: ubuntu-latest
    needs: ["load-commit-message"]
    if: ${{ needs.load-commit-message.outputs.commit-message != '' }} 
    outputs:
      log-body: ${{ steps.generate-body.outputs.body }}
    steps:
      - uses: actions/checkout@v4 # 최신 버전 사용 권장
        with:
          fetch-depth: 0
      - name: Generate body
        id: generate-body
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          # git describe --tags --abbrev=0 명령어가 태그를 찾지 못할 경우를 대비하여 기본값 설정
          # 예를 들어, 첫 릴리즈 시 태그가 없을 수 있습니다.
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          
          if [ -z "$LAST_TAG" ]; then
            # 태그가 없으면 모든 커밋 로그를 가져옵니다.
            git_logs=$(git log --oneline)
          else
            # 태그가 있으면 해당 태그 이후의 커밋 로그를 가져옵니다.
            git_logs=$(git log "$LAST_TAG"..HEAD --oneline)
          fi

          git_logs="${git_logs//$'\n'/$'\n'- }"
          {
              echo "body<<$EOF"
              echo "- $git_logs"
              echo "$EOF"
          } >>"$GITHUB_OUTPUT"
        shell: bash

  update-version:
    name: 버전 번호 증가
    runs-on: ubuntu-latest
    needs: ["load-log"]
    if: ${{ needs.load-log.outputs.log-body != '' }}
    outputs:
      update-version: ${{ steps.update-version-file.outputs.update-version }}
    steps:
      - uses: actions/checkout@v4 # 최신 버전 사용 권장
      - name: update version file (local only for this job)
        id: update-version-file
        run: |
          new-version=$(echo ${{ needs.load-commit-message.outputs.version }} | awk -F. '{OFS="."; $3++; print}' )" 
          echo $new-version > VERSION
          echo "update-version=$(cat VERSION)" >> $GITHUB_OUTPUT
        shell: bash    
      
  create-tag:
    name: 새로운 버전으로 태그 생성
    runs-on: ubuntu-latest
    needs: ["update-version" , "load-log"]
    if: ${{ needs.update-version.outputs.update-version != '' }}
    permissions:
      contents: write # 릴리즈를 생성하려면 쓰기 권한이 필요합니다.
    outputs:
      tag-exists: ${{ steps.create-tag.outputs.tag_exists }}
    steps:
      - uses: actions/checkout@v4 # 최신 버전 사용 권장
        with:
          fetch-depth: 0
      - uses: rickstaa/action-create-tag@v1
        id: create-tag
        with:
          tag: v${{ needs.update-version.outputs.update-version }} # 태그 이름에 'v' 접두사 추가 권장
          tag_exists_error: true
          message: ${{ needs.load-log.outputs.log-body }}

  create-release:
    name: 릴리즈 생성
    runs-on: ubuntu-latest
    needs: ["load-commit-message", "load-log", "create-tag", "update-version"]
    if: ${{ needs.create-tag.outputs.tag-exists == 'false' }} 
    permissions:
      contents: write # 릴리즈를 생성하려면 쓰기 권한이 필요합니다.
    steps:
      - uses: actions/checkout@v4 # 최신 버전 사용 권장
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ needs.update-version.outputs.update-version }} # 태그 이름에 'v' 접두사 추가 권장
          name: "Release v${{ needs.update-version.outputs.update-version }}"
          body: ${{ needs.load-log.outputs.log-body }}
          draft: false
          prerelease: false
  
  auto-git-push:
    name: VERSION 파일 업데이트 및 푸시
    runs-on: ubuntu-latest
    needs: ["update-version", "create-tag", "create-release"]
    # 핵심 변경:
    # 2. needs.create-tag.outputs.tag-exists == 'false' 조건을 유지하여 태그가 이미 존재하면 푸시하지 않습니다.
    if: ${{  needs.create-tag.outputs.tag-exists == 'false' }}
    permissions:
      contents: write # 변경 사항을 푸시하려면 쓰기 권한이 필요합니다.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # 가장 중요한 변경: GH_PAT 대신 기본 GITHUB_TOKEN을 사용합니다.
          # GITHUB_TOKEN으로 github-actions[bot]이 푸시한 내용은 새로운 워크플로우 실행을 트리거하지 않습니다.
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Git 히스토리를 가져오기 위해 필요
      - name: Update Version File, Commit, and Push
        id: git-push-version
        run: |
          NEW_VERSION="${{ needs.update-version.outputs.update-version }}"
           # VERSION 파일에 새 버전 쓰기
          echo "$NEW_VERSION" > VERSION
           # Git 사용자 설정
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
           # VERSION 파일을 스테이징
          git add VERSION
           # 커밋할 변경 사항이 있는지 확인
          if git diff --staged --quiet; then
              echo "No changes to VERSION file. Skipping commit and push."
          else
              # 변경 사항 커밋
              git commit -m "chore: Update version to $NEW_VERSION"
              
              # 변경 사항 푸시
              echo "Pushing updated VERSION file..."
              git push origin main # 또는 대상 브랜치 이름
              echo "VERSION file pushed successfully."
          fi
        shell: bash