name: Create Release from Version File
on:
  push:
    branches:
      - main  # 또는 원하는 브랜치
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 태그를 가져오기 위해 필요

      - name: Load Version from File
        id: version  # 이 ID를 사용하여 출력 값을 참조합니다.
        uses: actions/github-script@v7  # 최신 버전으로 업데이트
        with:
          script: |
            const fs = require('fs');
            const versionFile = './VERSION';  // 버전 파일 경로
            const version = fs.readFileSync(versionFile, 'utf8').trim();
            return version;


      - name: Create Tag and Release
        uses: mathieudutour/github-tag-action@v6.1 # 최신 버전으로 업데이트
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.result }} # 버전 파일에서 읽은 버전 사용
          tag_prefix: "v" # 필요에 따라 접두사 추가

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1 # 최신 버전으로 업데이트
        with:
          tag: "v${{ steps.version.outputs.result }}" #  버전 prefix를 포함하여 릴리즈 생성
          name: "Release ${{ steps.version.outputs.result }}" # 릴리즈 제목
          body: "Release notes for version ${{ steps.version.outputs.result }}" # 릴리즈 노트 (선택 사항)
          draft: false # 초안으로 만들지 여부 (선택 사항)
          prerelease: false # 시험판 릴리즈 여부 (선택 사항)
          token: ${{ secrets.GITHUB_TOKEN }}