name: Auto Release

on:
  push:
    #tags:
    #  - 'v[0-9]+.[0-9]+.[0-9]+' # 'v1.0.0', 'v1.1.0' 등과 같은 태그를 인식합니다.
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 릴리즈를 생성하려면 쓰기 권한이 필요합니다.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 프로젝트 코드를 체크아웃합니다.

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 깃허브 토큰을 사용합니다.
        with:
          tag_name: ${{ github.ref }} # 푸시된 태그 이름을 사용합니다.
          release_name: Release ${{ github.ref }} # 릴리즈 이름에 태그 이름을 포함합니다.
          body: |
            This is an automated release based on the new tag.
            
            **What's new:**
            - You can add release notes here.
            - This section can be a changelog.
          draft: false # 초안(Draft) 릴리즈가 아닌 바로 게시(Publish)합니다.
          prerelease: false # 프리릴리즈(Pre-release) 여부를 설정합니다.