name: CI/CD 파이프라인 - 버전 업데이트 및 릴리즈

on:
  workflow_dispatch: # 트리거를 수동으로 변경하거나 다른 워크플로우의 신호를 받도록 변경
    branches: [ "main" ]
  
# 기존의 push 트리거는 제거하거나 주석 처리하여, ci.yml의 성공 후에만 실행되도록 합니다.
# on:
#   push:
#     branches: [ "main" ]

jobs:
  pre-version:
    name: 현재 파일 버전 로드
    runs-on: ubuntu-latest
    outputs:
      pre-version: ${{ steps.read-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 태그 및 전체 히스토리를 가져오기 위해 필요
      - name: VERSION 파일에서 현재 버전 추출
        id: read-version
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const versionFile = './VERSION';
            const version = fs.readFileSync(versionFile, 'utf8').trim();
            core.setOutput('version', version);

# 아래 내역은 푸쉬 이벤트로 workflow_dispatch를 함으로 해당 내역은 주석으로 테스트
#  load-commit-message:
#    name: 커밋 메시지 로드
#    runs-on: ubuntu-latest
#    needs: ["pre-version"]
#    if: ${{ needs.pre-version.outputs.pre-version != '' }} 
#    outputs:
#      commit-message: ${{ steps.check.outputs.commit-message }}
#    steps:
#      - uses: actions/checkout@v4 # 최신 버전 사용 권장
#      - name: Check commit message
#        id: check
#        run: echo "commit-message=$(echo '${{ github.event.head_commit.message }}')" >> $GITHUB_OUTPUT
#        shell: bash

# 커밋 메시지가 없어졌음으로 여기는 버전을 참조하는 것으로 수정
  load-log:
    name: 로그에서 커밋된 로그 로드
    runs-on: ubuntu-latest
    # needs: ["load-commit-message"]
    needs: ["pre-version"]
    # if: ${{ needs.load-commit-message.outputs.commit-message != '' }} 
    if: ${{ needs.pre-version.outputs.pre-version != '' }} 
    outputs:
      log-body: ${{ steps.generate-body.outputs.body }}
    steps:
      - uses: actions/checkout@v4 # 최신 버전 사용 권장
        with:
          fetch-depth: 0
      - name: Generate body
        id: generate-body
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          # git describe --tags --abbrev=0 명령어가 태그를 찾지 못할 경우를 대비하여 기본값 설정
          # 예를 들어, 첫 릴리즈 시 태그가 없을 수 있습니다.
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          
          if [ -z "$LAST_TAG" ]; then
            # 태그가 없으면 모든 커밋 로그를 가져옵니다.
            git_logs=$(git log --oneline)
          else
            # 태그가 있으면 해당 태그 이후의 커밋 로그를 가져옵니다.
            git_logs=$(git log "$LAST_TAG"..HEAD --oneline)
          fi

          git_logs="${git_logs//$'\n'/$'\n'- }"
          {
              echo "body<<$EOF"
              echo "- $git_logs"
              echo "$EOF"
          } >>"$GITHUB_OUTPUT"
        shell: bash

  update-version:
    name: 버전 번호 증가
    runs-on: ubuntu-latest
    needs: ["load-log", "pre-version"]
    if: ${{ needs.load-log.outputs.log-body != '' }}
    outputs:
      update-version: ${{ steps.update-version-file.outputs.update-version }}
    steps:
      - uses: actions/checkout@v4 # 최신 버전 사용 권장
      - name: update version file (local only for this job)
        id: update-version-file
        # 'new-version' 변수명을 'new_version'으로 변경했습니다.
        # 변경된 변수명을 사용하여 파일에 쓰고, 출력합니다.
        run: |
          # 현재 버전 값을 가져옵니다.
          current_version="${{ needs.pre-version.outputs.pre-version }}"
          
          # 버전을 Major, Minor, Patch로 분리합니다.
          IFS='.' read -r major minor patch <<< "$current_version"
  
          # Patch 버전을 연산하기 전에 앞에 붙은 0을 제거하여 10진수로 처리합니다.
          # 예: "09" -> "9"
          patch="${patch##0}"
          
          # Patch 버전을 1 증가시킵니다.
          patch=$((patch + 1))
  
          # Patch 버전이 99를 초과하면 (즉, 100이 되면) Minor 버전을 증가시키고 Patch를 0으로 초기화합니다.
          if [ "$patch" -gt 99 ]; then
              patch=0
              minor=$((minor + 1))
              # 필요하다면 Minor 버전도 99를 초과할 때 Major 버전을 증가시키는 로직을 추가할 수 있습니다.
              # 예: if [ "$minor" -gt 99 ]; then minor=0; major=$((major + 1)); fi
          fi
          
          # 새로운 버전 문자열을 조합합니다.
          # printf "%02d" $patch 를 사용하여 패치 버전이 한 자리일 경우 앞에 0을 붙여 두 자리로 만듭니다.
          # 예: 0.0.9 -> 0.0.10 (패치 증가)
          # 예: 0.0.99 -> 0.1.00 (롤오버)
          new_version="${major}.${minor}.$(printf "%02d" $patch)"
          
          # VERSION 파일에 새 버전을 쓰고, GitHub Actions의 출력으로도 내보냅니다.
          echo "$new_version" > VERSION
          echo "update-version=$(cat VERSION)" >> "$GITHUB_OUTPUT"
        shell: bash
      
  create-tag:
    name: 새로운 버전으로 태그 생성
    runs-on: ubuntu-latest
    needs: ["update-version" , "load-log"]
    if: ${{ needs.update-version.outputs.update-version != '' }}
    permissions:
      contents: write # 릴리즈를 생성하려면 쓰기 권한이 필요합니다.
    outputs:
      tag-exists: ${{ steps.create-tag.outputs.tag_exists }}
    steps:
      - uses: actions/checkout@v4 # 최신 버전 사용 권장
        with:
          fetch-depth: 0
      - uses: rickstaa/action-create-tag@v1
        id: create-tag
        with:
          tag: v${{ needs.update-version.outputs.update-version }} # 태그 이름에 'v' 접두사 추가 권장
          tag_exists_error: true
          message: ${{ needs.load-log.outputs.log-body }}

  create-release:
    name: 릴리즈 생성
    runs-on: ubuntu-latest
    needs: ["load-log", "create-tag", "update-version"]
    if: ${{ needs.create-tag.outputs.tag-exists == 'false' }} 
    permissions:
      contents: write # 릴리즈를 생성하려면 쓰기 권한이 필요합니다.
    steps:
      - uses: actions/checkout@v4 # 최신 버전 사용 권장
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ needs.update-version.outputs.update-version }} # 태그 이름에 'v' 접두사 추가 권장
          name: "Release v${{ needs.update-version.outputs.update-version }}"
          body: ${{ needs.load-log.outputs.log-body }}
          draft: false
          prerelease: false
  
  auto-git-push:
    name: VERSION 파일 업데이트 및 푸시
    runs-on: ubuntu-latest
    needs: ["update-version", "create-tag", "create-release"]
    # 핵심 변경:
    # 2. needs.create-tag.outputs.tag-exists == 'false' 조건을 유지하여 태그가 이미 존재하면 푸시하지 않습니다.
    if: ${{  needs.create-tag.outputs.tag-exists == 'false' }}
    permissions:
      contents: write # 변경 사항을 푸시하려면 쓰기 권한이 필요합니다.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # 가장 중요한 변경: GH_PAT 대신 기본 GITHUB_TOKEN을 사용합니다.
          # GITHUB_TOKEN으로 github-actions[bot]이 푸시한 내용은 새로운 워크플로우 실행을 트리거하지 않습니다.
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Git 히스토리를 가져오기 위해 필요
      - name: Update Version File, Commit, and Push
        id: git-push-version
        run: |
          NEW_VERSION="${{ needs.update-version.outputs.update-version }}"
           # VERSION 파일에 새 버전 쓰기
          echo "$NEW_VERSION" > VERSION
           # Git 사용자 설정
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
           # VERSION 파일을 스테이징
          git add VERSION
           # 커밋할 변경 사항이 있는지 확인
          if git diff --staged --quiet; then
              echo "No changes to VERSION file. Skipping commit and push."
          else
              # 변경 사항 커밋
              git commit -m "chore: Update version to $NEW_VERSION"
              
              # 변경 사항 푸시
              echo "Pushing updated VERSION file..."
              git push origin main # 또는 대상 브랜치 이름
              echo "VERSION file pushed successfully."
          fi
        shell: bash